"""
email_service.py  –  Notifications Module
Sends HTML email alerts when High financial risk is detected.
Credentials loaded from .env file.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from html import escape

from config import require_email_config, require_smtp_sender_config


def _send_message(msg, settings):
    server = None
    try:
        server = smtplib.SMTP(settings.smtp_server, settings.smtp_port, timeout=20)
        server.starttls()
        server.login(settings.email_sender, settings.email_password)
        server.send_message(msg)
    except smtplib.SMTPException as e:
        raise RuntimeError(f"SMTP error while sending email: {str(e)}")
    except Exception as e:
        raise RuntimeError(f"Unexpected error while sending email: {str(e)}")
    finally:
        if server:
            try:
                server.quit()
            except Exception:
                pass


def send_email_alert(summary: dict, ai_result: dict = None):
    """
    Sends a styled HTML email alert for a business with High risk.

    Args:
        summary   : Financial summary dict from generate_financial_summary()
        ai_result : (Optional) AI insight dict from generate_ai()

    Raises:
        EnvironmentError  if email credentials are missing in .env
        RuntimeError      if SMTP send fails
    """

    settings = require_email_config()
    sender_email = settings.email_sender
    sender_password = settings.email_password
    receiver_email = settings.email_receiver
    smtp_server = settings.smtp_server
    smtp_port = settings.smtp_port

    risk_level = summary.get("risk_level", "Unknown")
    subject    = f"⚠ ARIA Alert – {risk_level} Risk Detected"

    risk_color = {
        "High":     "#ff4d4d",
        "Moderate": "#ffa500",
        "Low":      "#28a745"
    }.get(risk_level, "#333333")

    runway_days = summary.get("cash_runway_days")
    runway_display = "Stable (No Burn)" if runway_days is None else f"{runway_days} days"

    # ── HTML body ─────────────────────────────────────────────────────────
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color:{risk_color};">⚠ ARIA – Financial Risk Alert</h2>
        <hr>
        <h3>Financial Summary</h3>
        <table cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
            <tr><td><strong>Revenue</strong></td>
                <td>₹ {summary.get('revenue', 0)}</td></tr>
            <tr><td><strong>Expenses</strong></td>
                <td>₹ {summary.get('expenses', 0)}</td></tr>
            <tr><td><strong>Profit Margin</strong></td>
                <td>{summary.get('profit_margin', 0)} %</td></tr>
            <tr><td><strong>Cash Runway</strong></td>
                <td>{runway_display}</td></tr>
            <tr><td><strong>Risk Score</strong></td>
                <td>{summary.get('risk_score', 0)}</td></tr>
            <tr><td><strong>Risk Level</strong></td>
                <td style="color:{risk_color};font-weight:bold;">{risk_level}</td></tr>
        </table>
    """

    if ai_result and isinstance(ai_result, dict) and ai_result.get("analysis"):
        analysis = ai_result["analysis"]
        html_body += f"""
        <hr>
        <h3>🤖 AI Strategic Advisory</h3>
        <p><strong>Summary:</strong> {escape(str(analysis.get('summary', '')))}</p>
        <p><strong>Key Risk:</strong> {escape(str(analysis.get('key_risk', '')))}</p>
        <p><strong>Recommendation:</strong> {escape(str(analysis.get('recommendation', '')))}</p>
        <p><strong>Urgent Action Required:</strong>
           {'Yes ⚠' if analysis.get('urgent_action_required') else 'No'}</p>
        <p><strong>Confidence Score:</strong> {analysis.get('confidence_score', '')} / 95</p>
        """

    html_body += """
        <hr>
        <p style="font-size:12px;color:#888;">
            Generated by ARIA – Advanced Risk Intelligence Assistant
        </p>
    </body>
    </html>
    """

    # ── Build MIME message ────────────────────────────────────────────────
    msg           = MIMEMultipart("alternative")
    msg["From"]   = sender_email
    msg["To"]     = receiver_email
    msg["Subject"]= subject
    msg.attach(MIMEText(html_body, "html"))

    _send_message(msg, settings)
    print(f"Email alert sent to {receiver_email}")


def send_report_email(
    recipient_email: str,
    report_text: str,
    summary: dict,
    report_id: int | None = None,
    recommendation: dict | None = None,
):
    """Sends a saved ARIA report to the registered user email."""
    settings = require_smtp_sender_config()
    recipient = (recipient_email or "").strip()
    if not recipient:
        raise RuntimeError("Registered user email is missing.")

    risk_level = summary.get("risk_level", "Unknown")
    risk_score = summary.get("risk_score", "n/a")
    subject_id = f" #{report_id}" if report_id else ""
    subject = f"ARIA Saved Risk Report{subject_id} - {risk_level} Risk"

    analysis = (recommendation or {}).get("analysis", {}) if isinstance(recommendation, dict) else {}
    recommendation_html = ""
    if analysis:
        recommendation_html = f"""
        <h3>Recommendation</h3>
        <p><strong>Summary:</strong> {escape(str(analysis.get('summary', '')))}</p>
        <p><strong>Key Risk:</strong> {escape(str(analysis.get('key_risk', '')))}</p>
        <p><strong>Action:</strong> {escape(str(analysis.get('recommendation', '')))}</p>
        """

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5;">
        <h2>ARIA Saved Risk Report</h2>
        <p>Your saved report is attached as a text file.</p>
        <table cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
            <tr><td><strong>Report ID</strong></td><td>{escape(str(report_id or 'n/a'))}</td></tr>
            <tr><td><strong>Risk Level</strong></td><td>{escape(str(risk_level))}</td></tr>
            <tr><td><strong>Risk Score</strong></td><td>{escape(str(risk_score))}</td></tr>
            <tr><td><strong>Revenue</strong></td><td>Rs {escape(str(summary.get('revenue', 0)))}</td></tr>
            <tr><td><strong>Expenses</strong></td><td>Rs {escape(str(summary.get('expenses', 0)))}</td></tr>
        </table>
        {recommendation_html}
        <p style="font-size:12px;color:#667085;">Generated by ARIA - Advanced Risk Intelligence Assistant.</p>
    </body>
    </html>
    """

    msg = MIMEMultipart("mixed")
    msg["From"] = settings.email_sender
    msg["To"] = recipient
    msg["Subject"] = subject

    body = MIMEMultipart("alternative")
    body.attach(MIMEText(report_text, "plain", "utf-8"))
    body.attach(MIMEText(html_body, "html", "utf-8"))
    msg.attach(body)

    attachment = MIMEApplication(report_text.encode("utf-8"), _subtype="txt")
    attachment.add_header(
        "Content-Disposition",
        "attachment",
        filename=f"aria_risk_report_{report_id or 'current'}.txt",
    )
    msg.attach(attachment)

    _send_message(msg, settings)
    return {"recipient": recipient, "status": "sent"}


def send_otp_email(recipient_email: str, otp_code: str):
    """Sends a one-time registration verification code."""
    settings = require_smtp_sender_config()
    recipient = (recipient_email or "").strip()
    if not recipient:
        raise RuntimeError("Recipient email is missing.")

    code = str(otp_code or "").strip()
    if len(code) != 6:
        raise RuntimeError("OTP code must be a 6-digit value.")

    subject = "ARIA email verification code"
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5;">
        <h2>Verify your ARIA account</h2>
        <p>Use this one-time code to finish registration:</p>
        <div style="font-size:28px;font-weight:700;letter-spacing:6px;padding:12px 0;">
            {escape(code)}
        </div>
        <p>This code expires in 10 minutes. If you did not request this, ignore this email.</p>
        <p style="font-size:12px;color:#667085;">Generated by ARIA - Advanced Risk Intelligence Assistant.</p>
    </body>
    </html>
    """
    plain_body = (
        "Verify your ARIA account\n\n"
        f"Your one-time verification code is: {code}\n\n"
        "This code expires in 10 minutes."
    )

    msg = MIMEMultipart("alternative")
    msg["From"] = settings.email_sender
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(plain_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    _send_message(msg, settings)
    return {"recipient": recipient, "status": "sent"}
